spring:
  mvc:
    log-resolved-exception: true
  jackson:
    default-property-inclusion: NON_NULL
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
minio:
  url: http://localhost:9000
  username: minioadmin
  password: minioadmin
  blocksize: 6000000
  images-bucket-name: images