spring:
  mvc:
    log-resolved-exception: true
  jackson:
    default-property-inclusion: NON_NULL
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true